name: PR Build and Test

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

# 授予工作流写入权限，用于创建 Release 和上传产物
permissions:
  contents: write

# 定义环境变量
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

# 确保每个提交只运行一次工作流
concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # 任务 1: 检查 Git Tag 和 package.json 的版本是否一致
  check_tag_version:
    name: Check Release Tag and package.json Version Consistency
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check tag and package.json version
        id: get_version
        run: |
          TAG_REF="${GITHUB_REF##*/}"
          echo "Current tag: $TAG_REF"
          PKG_VERSION=$(jq -r .version package.json)
          echo "package.json version: $PKG_VERSION"
          if [[ "$TAG_REF" != "v$PKG_VERSION" ]]; then
            echo "Tag ($TAG_REF) does not match package.json version (v$PKG_VERSION)."
            exit 0 # TODO 这里使用 exit 0 是为了确保工作流继续执行，但可以根据需要调整逻辑
          fi
          echo "Tag and package.json version are consistent."
          echo "version=${PKG_VERSION}" >> $GITHUB_OUTPUT

  # 任务 2: 为 Windows, macOS, Linux, 和 Android 构建和发布
  build:
    name: Build and Release
    needs: check_tag_version
    strategy:
      fail-fast: false
      matrix:
        # 定义需要构建的平台和架构
        include:
          # Windows
          - os: windows-latest
            platform: windows
            target: x86_64-pc-windows-msvc
            arch: x86_64
          - os: windows-latest
            platform: windows
            target: aarch64-pc-windows-msvc
            arch: aarch64
          # macOS
          - os: macos-latest
            platform: macos
            target: aarch64-apple-darwin
            arch: aarch64
          - os: macos-latest
            platform: macos
            target: x86_64-apple-darwin
            arch: x86_64
          # Linux
          - os: ubuntu-22.04
            platform: linux
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu-22.04
            platform: linux
            target: aarch64-unknown-linux-gnu
            arch: aarch64
          # Android
          - os: ubuntu-22.04
            platform: android
            target: aarch64-linux-android
            arch: aarch64
          - os: ubuntu-22.04
            platform: android
            target: x86_64-linux-android
            arch: x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 安装 Rust Stable
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      # 添加 Rust 编译目标
      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      # Rust 缓存
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      # 仅在 Ubuntu 上安装依赖
      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libgtk-3-dev libssl-dev xdg-utils librsvg2-dev libappindicator3-dev  patchelf

      # 仅为 Android 平台安装额外的依赖
      - name: Install Android dependencies (android only)
        if: matrix.platform == 'android'
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      # 设置 Node.js 环境
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      # 设置 pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest

      # 安装前端依赖
      - name: Pnpm install
        run: pnpm i

      # Tauri 构建
      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.ANDROID_SIGNING_DEBUG_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_DEBUG_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_SIGNING_DEBUG_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_DEBUG_KEY_ALIAS }}
          ANDROID_KEY_PASS: ${{ secrets.ANDROID_SIGNING_DEBUG_KEY_ALIAS_PASSWORD }}
          DECOUPLED_MODE: ${{ matrix.platform != 'linux' && matrix.platform != 'android' && 'true' || '' }}
        with:
          # 使用 `check_tag_version` 任务的输出版本
          tagName: v${{ needs.check_tag_version.outputs.version }}
          releaseName: "Release v${{ needs.check_tag_version.outputs.version }}"
          releaseBody: "Automated release build for all platforms."
          tauriScript: pnpm
          args: --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-${{ matrix.platform }}-${{ matrix.arch }}-pr${{ github.event.number }}
          path: |
            src-tauri/target/release/bundle/**/*
            !src-tauri/target/release/bundle/**/debug/
          retention-days: 7

  comment-pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });

            let comment = `## 🔨 PR Build Results\n\n`;
            
            if (artifacts.artifacts.length > 0) {
              comment += `✅ Build completed successfully!\n\n`;
              comment += `### 📦 Download Artifacts:\n`;
            
              for (const artifact of artifacts.artifacts) {
                const platform = artifact.name.includes('macos') ? '🍎 macOS' : 
                                artifact.name.includes('ubuntu') ? '🐧 Linux' : 
                                artifact.name.includes('windows') ? '🪟 Windows' : '📱 Unknown';
                comment += `- ${platform}: [${artifact.name}](${artifact.archive_download_url})\n`;
              }
            
              comment += `\n💡 **How to test:**\n`;
              comment += `1. Download the artifact for your platform\n`;
              comment += `2. Extract the archive\n`;
              comment += `3. Install/run the application\n`;
              comment += `4. Report any issues in this PR\n\n`;
              comment += `⏰ Artifacts will be available for 7 days.\n`;
            } else {
              comment += `❌ Build failed. Please check the workflow logs for details.\n`;
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🔨 PR Build Results')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }